- id: format-yaml
  name: Format YAML with Prettier
  entry: npx prettier --write
  language: node
  types: [yaml]
  files: \.(yaml|yml)$

- id: no-debug
  name: Ensure no `dbg` statements or `#include <dbg.h>` included in source files.
  entry: ./validate-debug.sh
  language: script
  types_or: [c++, file]
  files: \.(cpp|c++|cxx|hpp|h++|hxx|cu|cuh)$
