- id: dbg-check
  name: Ensure no `dbg` statements, macros or expressions included in source files.
  entry: ./validate-dbg.sh
  language: script
  types: [text]

- id: pragma-once
  name: Ensure all header files have `#pragma once` before any other imports.
  entry: ./validate-pragma.sh
  language: script
  types_or: [c++, file]
  files: \.(hpp|h\+\+|hxx|cuh)$

- id: check-merge-conflict
  name: Check for merge-conflicts.
  entry: ./validate-merge-conflict.sh
  language: script
  types: [file]

- id: mypy
  name: MyPy
  entry: ./run-mypy.sh
  language: system
  types: [python]
