line-length = 100

[format]
quote-style = "double"
indent-style = "space"

[lint]
extend-select = [
  "ANN",    # flake8-annotations
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "COM818", # trailing-comma-on-bare-tuple
  "ERA",    # eradicate
  "F",      # Pyflakes
  "I",      # isort
  "ISC",    # flake8-implicit-str-concat
  "N",      # pep8-naming
  "PT",     # flake8-pytest-style
  "PYI",    # flake8-pyi
  "RET",    # flake8-return
  "RUF",    # Ruff-specific rules
  "SIM",    # flake8-simplify
  "UP",     # pyupgrade
  "W",      # Warning (whitespace)
]

extend-ignore = [
  "ANN401", # flake8-annotations: any-type
  "C408",   # flake8-comprehensions: unnecessary-collection-call
  "E501",   # pycodestyle: line-too-long
  "F811",   # Pyflakes: redefined-while-unused
  "N812",   # pep8-naming: lowercase-imported-as-non-lowercase
  "PLC0414",# Pylint: useless-import-alias
  "PT011",  # flake8-pytest-style: pytest-raises-too-broad
  "PT012",  # flake8-pytest-style: pytest-raises-with-multiple-statements
  "PT013",  # flake8-pytest-style: pytest-incorrect-pytest-import
  "PYI041", # flake8-pyi: redundant-numeric-union
  "RET504", # flake8-return: unnecessary-assign
  "S",      # flake8-bandit
  "SIM118", # flake8-simplify: in-dict-keys
  "TRY",    # tryceratops
]

extend-unfixable = [
  "B905",   # flake8-bugbear: zip-without-explicit-strict
  "B911",   # flake8-bugbear: batched-without-explicit-strict
  "B912",   # flake8-bugbear: pairwise-without-explicit-strict
]
preview = true

[lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = false

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
