name: Check README for Version

on:
  push:
    branches:
      - m
  pull_request:
    branches:
      - m

jobs:
  check-readme:
    uses: George-Ogden/actions/.github/workflows/readme-check.yaml@v4.6.4
    with:
      prefix: "rev: v"
