name: Tag New Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: George-Ogden/actions/.github/workflows/text-release.yaml@v3.1.0
